### ISSUE TITLE
Inquiry about FOV Parameters of the RGB Camera

### ISSUE THREAD

**Issue by shenweiwu** [BingqiShen/EMV-LIO#4]
I noticed that you are using 3 RGB cameras in the project, and I would like to gather more information regarding the camera's Field of View (FOV).

Specifically, I am interested in knowing the FOV size in the horizontal, vertical, or diagonal directions. 

Addtionally, I am curious to know if the combination of the three cameras used in your setup allows for complete coverage of a 360-degree environment. If so, I would appreciate any insights or details you can provide regarding the arrangement or configuration of the cameras to achieve this coverage.

**Comment by shenweiwu** [comment]
Is the FOV used the common 45°？

**Comment by BingqiShen** [comment]
> Is the FOV used the common 45°？

Sorry, I've been quite busy recently and just saw your message. The cameras we use in this project is [MER2-202-60GC-P](https://www.daheng-imaging.com/product/area-scan-cameras/daheng/mer2-g-p/1937.html)

The FOV of it depends on its focal length. In this project, the FOV of the camera is around 90°
